name: $(Build.DefinitionName)_$(Build.SourceBranchName)_1.00.00$(rev:.rrrr)

trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
      - Sources/Client/*

pool:
  vmImage: windows-latest

variables:
  - group: 'Pipelines Global'
  - name: Sources
    value: Sources/Client/Sources
  - name: Solution
    value: $(Sources)/SkySpeed.sln
  - name: BuildTarget
    value: Sources/Client/bin
  - name: ismain
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

jobs:
#------------------------------------------------> Build
- job: Build
  displayName: 'Build SkySpeed.sln'
  steps:
  - checkout: self
    lfs: true

  - task: NuGetCommand@2
    displayName: 'Restore SkySpeed.sln'
    inputs:
      command: 'restore'
      restoreSolution: '$(Solution)'
      feedsToUse: 'select'
      vstsFeed: '7a41d38d-d7f1-43d0-8cca-5d18c0fbaa38/9e686431-a607-4e44-aa7e-16730dfc0f71'

  - task: VSBuild@1
    displayName: 'Build SkySpeed.sln'
    inputs:
      solution: '$(Solution)'
      platform: '$(BuildPlatform)'
      configuration: '$(BuildConfiguration)'
      clean: true
      maximumCpuCount: true

  - publish: $(BuildTarget)
    artifact: PublishSkySpeed
    displayName: 'Publish SkySpeed artifacts'

#------------------------------------------------>  Set Git Tag on success (only main)
- job: GitTag
  dependsOn: Build
  displayName: Set Tag on Success
  condition: and(succeeded(), eq(variables.ismain, true))
  steps:
    - checkout: self
      persistCredentials: true
    - powershell: |
        Write-Host "Tagging Build with: $env:BUILD_BUILDNUMBER"
        $env:GIT_REDIRECT_STDERR` = '2>&1'
        git tag $env:BUILD_BUILDNUMBER
        git push origin $env:BUILD_BUILDNUMBER