name: $(Build.DefinitionName)_$(Build.SourceBranchName)_1.00.00$(rev:.rrrr)

trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
      - Sources/Service/*

pool:
  vmImage: windows-latest

variables:
  - group: 'Pipelines Global'
  - name: Sources
    value: Sources/Service/Sources
  - name: Solution
    value: $(Sources)/SkySpeedService.sln
  - name: SkySpeedServiceNugetPath
    value: Sources/Service/Deployment/Nuget
  - name: BuildTarget
    value: Sources/Service/bin
  - name: ismain
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

jobs:
#------------------------------------------------> Build
- job: Build
  displayName: 'Build SkySpeedService.sln'
  steps:
  - checkout: self
    lfs: true

  - task: NuGetCommand@2
    displayName: 'Restore SkySpeedService.sln'
    inputs:
      command: 'restore'
      restoreSolution: '$(Solution)'
      feedsToUse: 'select'

  - task: VSBuild@1
    displayName: 'Build SkySpeedService.sln'
    inputs:
      solution: '$(Solution)'
      platform: '$(BuildPlatform)'
      configuration: '$(BuildConfiguration)'
      clean: true
      maximumCpuCount: true
  
  - task: NuGetCommand@2
    displayName: 'SkySpeedService NuGets pack'
    inputs:
      command: 'pack'
      packagesToPack: '$(SkySpeedServiceNugetPath)/*.nuspec'
      packDestination: '$(Build.ArtifactStagingDirectory)\packages'
      versioningScheme: 'byBuildNumber'

  - task: NuGetCommand@2
    displayName: 'SkySpeedService NuGets push'
    condition: and(succeeded(), eq(variables.ismain, true))
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)\packages\*.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '7a41d38d-d7f1-43d0-8cca-5d18c0fbaa38/9e686431-a607-4e44-aa7e-16730dfc0f71'

  - publish: $(BuildTarget)
    artifact: PublishSkySpeedService
    displayName: 'Publish SkySpeedService artifacts'

#------------------------------------------------>  Set Git Tag on success (only main)
- job: GitTag
  dependsOn: Build
  displayName: Set Tag on Success
  condition: and(succeeded(), eq(variables.ismain, true))
  steps:
    - checkout: self
      persistCredentials: true
    - powershell: |
        Write-Host "Tagging Build with: $env:BUILD_BUILDNUMBER"
        $env:GIT_REDIRECT_STDERR` = '2>&1'
        git tag $env:BUILD_BUILDNUMBER
        git push origin $env:BUILD_BUILDNUMBER